# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [faheemkog-x-bot1, user2]
patreon: # Replace with a single Patreon faheemkog-x-bot
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-gethub/package-jasion e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay faheemkog-x-bot
issuehunt: # Replace with a single IssueHunt faheemkog-x-bot
otechie: # Replace with a single Otechie faheemkog-x-bot
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-faheemkog-x-bot e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
